# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('c_slug', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('c_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('p_slug', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='c_pais',
            field=models.ForeignKey(default='Spain', on_delete=django.db.models.deletion.CASCADE, to='escorts.Pais'),
        ),
    ]
