# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='c_pais',
            field=models.ForeignKey(default='SP', on_delete=django.db.models.deletion.CASCADE, to='escorts.Pais'),
        ),
    ]
