# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0002_auto_20180916_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciudad',
            new_name='Provincia',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='p_nombre',
            new_name='pa_nombre',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='p_slug',
            new_name='pa_slug',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='c_nombre',
            new_name='pr_nombre',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='c_pais',
            new_name='pr_pais',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='c_slug',
            new_name='pr_slug',
        ),
    ]
