# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escorts', '0003_auto_20180916_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_slug', models.CharField(max_length=10)),
                ('es_nombre', models.CharField(max_length=30)),
                ('es_apellido', models.CharField(max_length=30)),
                ('es_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escorts.Pais')),
                ('es_provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escorts.Provincia')),
                ('es_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
