# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('escorts', '0004_escort'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Opcional. Por favor suministre su foto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
