# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0008_escort_es_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escort',
            name='es_slug',
            field=models.CharField(max_length=15),
        ),
    ]
