# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0009_auto_20180917_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('du_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sv_nombre', models.CharField(max_length=30)),
                ('sv_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escorts.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosEscort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('se_duracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escorts.Duracion')),
                ('se_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escorts.Servicios')),
            ],
        ),
    ]
