# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0010_duracion_servicios_serviciosescort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escort',
            old_name='es_foto_1',
            new_name='es_carpeta',
        ),
    ]
