# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0012_remove_escort_es_carpeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HestiaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hi_carrusel_1_imagen', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('hi_carrusel_1_descripcion', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('hi_carrusel_2_imagen', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('hi_carrusel_2_descripcion', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('hi_carrusel_3_imagen', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('hi_carrusel_3_descripcion', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
