# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0013_hestiainfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hestiainfo',
            old_name='hi_carrusel_1_imagen',
            new_name='hi_carrusel_1_titulo',
        ),
        migrations.AddField(
            model_name='hestiainfo',
            name='hi_carrusel_2_titulo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hestiainfo',
            name='hi_carrusel_3_titulo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hestiainfo',
            name='hi_carrusel_cantidad',
            field=models.IntegerField(default=3),
        ),
    ]
