# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0014_auto_20180930_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hestiainfo',
            name='hi_carrusel_2_imagen',
        ),
        migrations.RemoveField(
            model_name='hestiainfo',
            name='hi_carrusel_3_imagen',
        ),
    ]
