# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0016_hestiainfo_hi_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='es_telefono',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
