# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0017_escort_es_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='es_correo',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
