# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0020_auto_20181002_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='es_ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escorts.Ciudad'),
        ),
        migrations.AlterField(
            model_name='escort',
            name='es_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escorts.Provincia'),
        ),
    ]
