# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0022_serviciosescort_se_escort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_nombre', models.CharField(max_length=30)),
                ('ca_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escorts.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicasEscort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ce_caracteristica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escorts.Caracteristica')),
                ('ce_escort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escorts.Escort')),
            ],
        ),
    ]
